site_name: pyXY3d
site_description: A brief description of your project
site_url: https://mprib.github.io/pyxy3d/
repo_url: https://github.com/mprib/pyxy3d
repo_name: pyxy3d

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - Quickstart: getting_started/quickstart.md
  - Documentation:
      - User Guide: documentation/user_guide.md
      - API Reference: documentation/api_reference.md
  - Examples:
      - Example 1: examples/example1.md
      - Example 2: examples/example2.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
