CreationDate = 2023-02-07T08:31:15.128437

[cam_0]
port = 0
resolution = [ 640, 480,]
rotation_count = 0
exposure = -6
grid_count = 0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,],]

[cam_1]
port = 1
resolution = [ 1280, 720,]
rotation_count = 0
exposure = -3
grid_count = 0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,],]

[cam_2]
port = 2
resolution = [ 1280, 720,]
rotation_count = 0
exposure = -4
grid_count = 0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,],]

[cam_3]
port = 3
resolution = [ 1280, 720,]
rotation_count = 0
exposure = -4
grid_count = 0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,],]

[cam_4]
port = 4
resolution = [ 1280, 720,]
rotation_count = 0
exposure = -7
grid_count = 0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,],]

[charuco]
columns = 4
rows = 5
board_height = 11.0
board_width = 8.5
dictionary = "DICT_4X4_1000"
units = "inch"
aruco_scale = 0.75
square_size_overide_cm = 5.4
inverted = true
