CreationDate = 2022-10-22T11:10:05.513575

[charuco]
columns = 5
rows = 4
board_height = 14
board_width = 11
dictionary = "DICT_4X4_50"
units = "inch"
aruco_scale = 0.75
inverted = false

[cam_1]
port = 1
resolution = [ 640, 480,]
rotation_count = 0

[cam_0]
port = 0
resolution = [ 640, 480,]
rotation_count = 0

[cam_2]
port = 2
resolution = [ 640, 480,]
rotation_count = 0
