CreationDate = 2023-04-19T12:17:53.271704

[cam_0]
port = 0
size = [ 640, 480,]
rotation_count = 0
exposure = -7.0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,],]

[cam_1]
port = 1
size = [ 1280, 960,]
rotation_count = 0
exposure = -7.0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,],]

[charuco]
columns = 4
rows = 5
board_height = 11.0
board_width = 8.5
dictionary = "DICT_4X4_1000"
units = "inch"
aruco_scale = 0.75
square_size_overide_cm = 5.4
inverted = true
